### ISSUE TITLE
new metadata attribute: 'encryption' error

### ISSUE THREAD

**Issue by JorjMcKie** [rk700/python-fitz#10]
The metadata key 'encryption' shows 'None' (the string) instead of None.
The other key / value entries are correct.

**Comment by rk700** [comment]
https://github.com/rk700/python-fitz/commit/83b16f842706b73627056d9bfa6fc66dd0041352 should fix it.

**Comment by JorjMcKie** [comment]
There is a type in fitz.i:
'enctypion' instead of 'encryption'.

**Test output with encryption set:**
>>> ================================ RESTART ================================
>>> 
>>> doc.needsPass
1
>>> doc.metadata
{'producer': None, 'format': 'PDF 1.6', 'author': None, 'modDate': None, 'keywords': None, 'title': None, 'creationDate': None, 'creator': None, 'enctypion': False, 'subject': None}

**Test output with encryption unset:**
>>> ================================ RESTART ================================
>>> 
>>> doc.needsPass
0
>>> doc.metadata
{'producer': 'iText 2.1.7 by 1T3XT', 'format': 'PDF 1.6', 'author': None, 'modDate': "D:20150530024656-04'30'", 'keywords': None, 'title': None, 'creationDate': "D:20150506084312+02'00'", 'creator': 'pdfsam-console (Ver. 2.4.3e)', 'enctypion': False, 'subject': None}

**Comment by JorjMcKie** [comment]
After changing 'enctypion' => 'encryption':
**Test output with no encryption:**
>>> doc.needsPass
0
>>> doc.metadata
{'producer': 'iText 2.1.7 by 1T3XT', 'format': 'PDF 1.6', **'encryption': None,** 'author': None, 'modDate': "D:20150530024656-04'30'", 'keywords': None, 'title': None, 'creationDate': "D:20150506084312+02'00'", 'creator': 'pdfsam-console (Ver. 2.4.3e)', 'subject': None}

**Test output with encryption:**
>>> doc.needsPass
1
>>> doc.metadata
{'producer': None, 'format': 'PDF 1.6',** 'encryption': False,** 'author': None, 'modDate': None, 'keywords': None, 'title': None, 'creationDate': None, 'creator': None, 'subject': None}

Should be **'encryption': True** iff needsPass is True

**Comment by rk700** [comment]
Oops, sorry. Should be okay now.

BTW I just resigned and will move to another city for a new job from June. So maybe I would not be able to respond in time recently.

**Comment by JorjMcKie** [comment]
I wish you all the best! Must be a big change ...
May I ask where you will go? Will you start your new job right on Monday then?

**Comment by rk700** [comment]
Thank you. I'll leave from Beijing for Shanghai, and the job will start from Wed. Actually I happened to have some time for this project because I quit the job, and I'm afraid that the progress will become slower when the new work starts.

**Comment by JorjMcKie** [comment]
Done! here are the test outputs:
**With encryption:**
>>> doc.needsPass
1
>>> doc.metadata
{'producer': None, 'format': 'PDF 1.6', 'encryption': 'Standard V4 R4 128-bit RC4', 'author': None, 'modDate': None, 'keywords': None, 'title': None, 'creationDate': None, 'creator': None, 'subject': None}

**Without encryption:**
>>> doc.needsPass
0
>>> doc.metadata
{'producer': 'iText 2.1.7 by 1T3XT', 'format': 'PDF 1.6', 'encryption': None, 'author': None, 'modDate': "D:20150530033851-04'30'", 'keywords': None, 'title': None, 'creationDate': "D:20150506084312+02'00'", 'creator': 'pdfsam-console (Ver. 2.4.3e)', 'subject': None}

**Comment by JorjMcKie** [comment]
Ah, ok.
Well, I am sure your new job will require at least as much attention as your last one ...
Unfortunately, my C expertise is close to zero ...
But for the rest of the work: I do have time because I have retired and can indulge in my hobbies ...
Wish you a successfull start next Wednesday!
