### ISSUE TITLE
Python list of outline entries?

### ISSUE THREAD

**Issue by JorjMcKie** [rk700/python-fitz#11]
As new print functions have now been added to outline: would it be a big effort to also add a function that creates a Python list? Like the one in this demo program?
I guess that many future users will not really care for following the single entries with `outline.down` / `outline.next`, but rather be interested in a complete list in one shot.
In addition: people with non-standard encodings (like myself with German) want to get their characters printed correctly, so they would need to catch the output of `outline.saveText` / `outline.saveXML` somehow and decode it appropriately.
A potentially quick solution: could the output of the save functions be optionally redirected (into a string)?

**Comment by rk700** [comment]
The `saveXML` and `saveText` functions are just imported from mupdf. I don't think they are helpful too. Having the save functions return python string is a good idea.

**Comment by JorjMcKie** [comment]
I found out how to modify the SWIG interface file, such that this feature is provided as part of the ``Document`` class: ``Document.outlineList``.
