### ISSUE TITLE
Documentation review

### ISSUE THREAD

**Issue by JorjMcKie** [rk700/python-fitz#17]
Hi @rk700 and @ousia,
hope you are well.
I have made an effort to complete the python-fitz documentation. Obviously, I have taken version 1.2 as a starting point, but a lot has changed in 1.7. Therefore a lot had to be adjusted in the docu as well ... I do believe however, that what we have now can be called a close-to-final version 0.9.

If you could be so kind and give it a critical review - time permitting - and let me know of any required or nice-to-have changes?

The doc directory contains a sub dir ``html``, from which the html version can be invoked via index.html as usual.  
As a convenience, the doc directory also contains other technical versions, namely CHM (Windows help file), EPUB (e-book) and PDF. The contents are all in sync, they all have been created with sphinx from the same source.

**Comment by rk700** [comment]
@JorjMcKie Thank you so much for the work! The document looks great! I like the code snippet:)

And I think it's OK to close this issue since the usage is covered very well.

**Comment by JorjMcKie** [comment]
@rk700, I still have two open questions for you concerning documentation:
 1) ``Link.refs``: What does this mean? What is it good for?
 2) What does the function ``Pixmap.interpolate()`` do?

**Comment by rk700** [comment]
@JorjMcKie, 
Link.refs should not be exposed to user since it's the reference count. I've removed it.
Pixmap.interpolate is actually an integer. I added the description in the document source .txt file, though the html file is not updated since I'm not quite sure about the sphinx command.

**Comment by JorjMcKie** [comment]
@rk700,
thanks a lot. Updated the docu and will upload new version shortly.
Concerning spinx: never mind, I have the environment set up on my computer. So it is an easy thing for me.
