### ISSUE TITLE
Simplified installation

### ISSUE THREAD

**Issue by JorjMcKie** [rk700/python-fitz#18]
@rk700, I have simplified the installation process as planned:
We now have new directories containing the **generated MuPDF libraries** for each platform python-fitz will support. For now, these are ``LibLinux`` and ``LibWin32``.
For example, ``LibWin32`` contains ``libmupdf.lib`` and ``libthirdparty.lib``.
That should be the case for ``LibLinux`` as well ... could you please upload your Linux libraries to the Linux library?
The ``setup.py`` script has already been updated accordingly, the documentation is updated as well.
Thanks and best regards

**Comment by rk700** [comment]
Linux libraries uploaded.
