### ISSUE TITLE
minimal sample?

### ISSUE THREAD

**Issue by ousia** [rk700/python-fitz#2]
I wonder whether it would be possible to include a minimal demo that displays a given PDF file (selected from the command line) and that goes page up and page down.

I mean something similar to the [demo from poppler-python](https://bazaar.launchpad.net/~poppler-python/poppler-python/trunk/view/head:/demo/demo-poppler.py).

**Comment by JorjMcKie** [comment]
ousia,
I am working on an example as you are looking for. Hopefully I can put it on the wiki pages later today.
As a heads up: based on Python 2.7.9 and wxWidgets / wxPython it will display a PDF with forward / backward scroll.

**Comment by JorjMcKie** [comment]
@ousia 
If you are still interested, have a look at the PDF_display.py example in the demo folder. I tried to keep it simple - with obvious drawbacks onthe functionality side: However:
* starting it with a PDF-file parameter, it will display it in a scrollable window with buttons for previous / next and a field for direct jump to any page.
* rendering fully works at an amazing speed

NB:
There also is an example in wiki for pulling out a the document's outline in Python list format. For my reuqirements, this is more practical than a complicated journey through some dubious entry trees.

**Comment by ousia** [comment]
@JorjMcKie, many thanks for the sample.
