### ISSUE TITLE
git repository missing fitz.h file

### ISSUE THREAD

**Issue by J-A-M** [rk700/python-fitz#3]
The line

#include <fitz.h>

is in fitz/ctx.h and fitz/fitz_wrap.c

The file fitz.h is missing from the git repository

**Comment by JorjMcKie** [comment]
J-A-M:
If I understand you right, "fitz.h" is part of the mupdf download, not part of this repository.

**Comment by J-A-M** [comment]
Hi, Yep I realise that now.  Better instructions on compilation required.

**Comment by JorjMcKie** [comment]
Agree - I am just doing a little work on this. If you use WIndows, maybe have a look at the wiki.
I posted my installation experience there. Since yesterday, my stuff is running ... :)
