### ISSUE TITLE
building on windows

### ISSUE THREAD

**Issue by rk700** [rk700/python-fitz#6]
MSVC only supports c89, while our wrapper is in c99 standard.

We may need to do some conversion on the code.

**Comment by rk700** [comment]
Let's see whether https://github.com/rk700/python-fitz/commit/20c89f69988f3ddfe9733c54b9fb4e0f9c31bffd will fix it.

**Comment by JorjMcKie** [comment]
Intermediate good news from the WIndows front:
Compile + link successfull!!!
You obviously managed to get rid of C99 stuff ...
Will no go testing the beast ...

**Comment by JorjMcKie** [comment]
Another success:
demo.py is working correctly under windows!
