### ISSUE TITLE
Buffer Overrun?

### ISSUE THREAD

**Issue by JorjMcKie** [rk700/python-fitz#7]
While rendering many pages of a larger, complex PDF I get an exception with the message "cannot render page".
In my case this happens after around 50 pages rendering a PDF with 100 pages and a total size of 14 MB.
I have sent @rk700 a mail with the attached ZIP of the PDF.
Hope his mailbox can deal with attachments of this size (it's still 11 MB).

**Comment by rk700** [comment]
I can replay this bug on my machine. Will delve into it and see what happens.

**Comment by rk700** [comment]
I made a mistake when using `fz_try` `fz_catch` block in which the exception stack is never popped.
https://github.com/rk700/python-fitz/commit/53f4a3c428e38f59f04b5e262dbf0fa111056bbf should fix this.

**Comment by JorjMcKie** [comment]
Result of re-running the test and many more: the error is gone.
Everything else continues to work.
WOW what a speed!
