### ISSUE TITLE
I am working on the new documentation ...

### ISSUE THREAD

**Issue by JorjMcKie** [rk700/python-fitz#9]
Having the 1.2 stuff I am trying to find a way to present the new python-fitz, esp. to new users.
1) in order to put versions online we need a doc directory again. I obviously cannot create one
2) Apart from documenting the many changed details (renamed functions, variables, deleted / new objects), I have decided to create a tutorial for using fitz. It should explain the main functions in a simple step-by-step manner, and not try to be complete, but definitely be easy to understand.

Side questions:
A) There is no way, MuPDF can access meta information from a PDF (like author, subject, ...) - right?
B) MuPDF cannot write out PDFs in a selected manner, like "take only page 3-7, and 11-21", right?
C) MuPDF cannot change a PDF's meta data (like above, or even a changed outline tree), right?

**Comment by rk700** [comment]
@JorjMcKie, right, an API reference is necessary, as well as a good tutorial. What kind of document is not decided yet. And I think you can create new directory in your local repo and then git push to the github.

I did some research on mupdf source. Manipulating PDF, like split or merge, needs to reconstruct PDF, and there's no API for doing that. We may put it in the next version. For now, I can add a metadata field to the document class, and some other features like dealing with encrypted documents.

**Comment by ousia** [comment]
@JorjMcKie, I just wanted to say thank you for the updated documentation.
